products:
  number: 100
  load: true

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/r3}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:root}
  dbcp2:
    max-wait-millis: 30000
    validation-query: SELECT 1
    validation-query-timeout: 30
  jpa:

    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
    show-sql: true
springdoc:
  pathsToMatch: /api/**
